In [14]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

%pylab inline
newsgroups_train = fetch_20newsgroups(subset='train')
newsgroups_test = fetch_20newsgroups(subset='test')

Populating the interactive namespace from numpy and matplotlib


/Users/admin/myenv/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['clf']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [15]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=100)
cv.fit(newsgroups_train['data'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=100, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [3]:
X_train = cv.transform(newsgroups_train['data'])
X_test = cv.transform(newsgroups_test['data'])

y_train = newsgroups_train['target']
y_test = newsgroups_test['target']

In [16]:
train_mask = (y_train <= 1)
test_mask = (y_test <= 1)

X_train = X_train[train_mask]
X_test = X_test[test_mask]

y_train = y_train[train_mask]
y_test = y_test[test_mask]

In [17]:
X_train

<1064x100 sparse matrix of type '<class 'numpy.longlong'>'
	with 41977 stored elements in Compressed Sparse Row format>

In [41]:
print(X_train.todense())

[[2 0 0 ... 1 1 0]
 [0 1 0 ... 1 2 0]
 [1 5 0 ... 1 2 1]
 ...
 [0 2 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 1 1 0]]


In [19]:
%%time
clf = LogisticRegression(random_state=134).fit(X_train, y_train)

CPU times: user 16.7 ms, sys: 1.5 ms, total: 18.2 ms
Wall time: 16.7 ms


/Users/admin/myenv/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [20]:
clf.coef_

array([[ 0.21064376, -0.10965627,  0.70735825,  0.49613689, -0.41876053,
         0.09260234,  0.60236322,  0.00962276,  0.13619567, -0.33873586,
         0.44945321,  0.65983335, -0.11477979, -0.25034791, -0.22272227,
         0.31662904, -0.38856023,  1.45758623,  0.12285304, -0.11310338,
         0.10794384, -0.14132508,  0.28709541, -0.11701379, -0.40852462,
        -0.28762805,  0.43593535,  0.14101981,  0.81961088,  0.12582573,
        -0.02303851,  0.2381653 , -0.02167271, -0.79619132, -1.07591654,
         0.12137818,  0.10990154, -0.08211524,  0.06640203, -0.08618722,
        -0.04670423,  0.47166025,  0.01817298,  0.44838027, -0.57981341,
         0.10669723,  0.2658698 ,  0.33815711, -0.11279431, -0.2699463 ,
         0.04144119,  0.05705041, -0.3154793 , -0.04117832, -0.22714562,
         0.12551303, -0.44644014,  0.66106443, -0.25297701,  0.88986794,
        -0.11582239,  0.54220699, -1.64542881,  0.25399062, -1.29627022,
         0.06409328, -0.03004501, -0.0297608 ,  0.8

In [21]:
cv.vocabulary_

{'from': 27,
 'edu': 24,
 'my': 49,
 'subject': 68,
 'what': 90,
 'is': 39,
 'this': 79,
 'nntp': 51,
 'posting': 63,
 'host': 35,
 'organization': 59,
 'university': 82,
 'of': 54,
 'lines': 44,
 'was': 86,
 'if': 37,
 'out': 61,
 'there': 75,
 'could': 20,
 'me': 47,
 'on': 55,
 'the': 71,
 'other': 60,
 'it': 40,
 'to': 81,
 'be': 12,
 'were': 89,
 'in': 38,
 'all': 1,
 'know': 42,
 'can': 18,
 'or': 58,
 'you': 98,
 'have': 32,
 'by': 16,
 'your': 99,
 'for': 26,
 'article': 8,
 'who': 93,
 'their': 72,
 'with': 95,
 'and': 5,
 'are': 7,
 'will': 94,
 'so': 66,
 'well': 88,
 'up': 83,
 'as': 9,
 'new': 50,
 'than': 69,
 'that': 70,
 'does': 22,
 'any': 6,
 'when': 91,
 'an': 4,
 'but': 15,
 'don': 23,
 'had': 30,
 'more': 48,
 'has': 31,
 'about': 0,
 'like': 43,
 'just': 41,
 'how': 36,
 'good': 29,
 'some': 67,
 'people': 62,
 'use': 85,
 'get': 28,
 'only': 57,
 'time': 80,
 'at': 10,
 're': 64,
 'com': 19,
 'writes': 97,
 'do': 21,
 'no': 52,
 'am': 3,
 'we': 87,
 'because': 13

In [22]:
[(k,v) for k, v in sorted(cv.vocabulary_.items(), key=lambda item: item[1])]

[('about', 0),
 ('all', 1),
 ('also', 2),
 ('am', 3),
 ('an', 4),
 ('and', 5),
 ('any', 6),
 ('are', 7),
 ('article', 8),
 ('as', 9),
 ('at', 10),
 ('ax', 11),
 ('be', 12),
 ('because', 13),
 ('been', 14),
 ('but', 15),
 ('by', 16),
 ('ca', 17),
 ('can', 18),
 ('com', 19),
 ('could', 20),
 ('do', 21),
 ('does', 22),
 ('don', 23),
 ('edu', 24),
 ('even', 25),
 ('for', 26),
 ('from', 27),
 ('get', 28),
 ('good', 29),
 ('had', 30),
 ('has', 31),
 ('have', 32),
 ('he', 33),
 ('his', 34),
 ('host', 35),
 ('how', 36),
 ('if', 37),
 ('in', 38),
 ('is', 39),
 ('it', 40),
 ('just', 41),
 ('know', 42),
 ('like', 43),
 ('lines', 44),
 ('max', 45),
 ('may', 46),
 ('me', 47),
 ('more', 48),
 ('my', 49),
 ('new', 50),
 ('nntp', 51),
 ('no', 52),
 ('not', 53),
 ('of', 54),
 ('on', 55),
 ('one', 56),
 ('only', 57),
 ('or', 58),
 ('organization', 59),
 ('other', 60),
 ('out', 61),
 ('people', 62),
 ('posting', 63),
 ('re', 64),
 ('should', 65),
 ('so', 66),
 ('some', 67),
 ('subject', 68),
 ('than', 69

In [23]:
names = [k for k, v in sorted(cv.vocabulary_.items(), key=lambda item: item[1])]
coef = clf.coef_.ravel()

In [24]:
df = pd.DataFrame(np.array([coef, names]).T, columns=['coef', 'names'])
df.sort_values('coef')

coef         names
75  -0.019343720281879747         there
32   -0.02167271202684253          have
30  -0.023038507737846315           had
67  -0.029760799389389768          some
66   -0.03004500608752948            so
..                    ...           ...
68     0.8886500340260675       subject
59     0.8898679382351292  organization
85      0.971022394541282           use
82     0.9875234933671605    university
17      1.457586230969981            ca

[100 rows x 2 columns]

Populating the interactive namespace from numpy and matplotlib


/Users/admin/myenv/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['clf']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [11]:
import eli5
eli5.explain_weights(clf, feature_names=names)

Explanation(estimator="LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,\n                   intercept_scaling=1, l1_ratio=None, max_iter=100,\n                   multi_class='warn', n_jobs=None, penalty='l2',\n                   random_state=134, solver='warn', tol=0.0001, verbose=0,\n                   warm_start=False)", description="\nFeatures with largest coefficients.\nCaveats:\n1. Be careful with features which are not\n   independent - weights don't show their importance.\n2. If scale of input features is different then scale of coefficients\n   will also be different, making direct comparison between coefficient values\n   incorrect.\n3. Depending on regularization, rare features sometimes may have high\n   coefficients; this doesn't mean they contribute much to the\n   classification result for most examples.\n", error=None, method='linear model', is_regression=False, targets=[TargetExplanation(target=1, feature_weights=FeatureWeights(pos=[FeatureWeight(feature='ca', weight=1.4575862354040092, std=None, value=None), FeatureWeight(feature='<BIAS>', weight=1.0768598755173704, std=None, value=None), FeatureWeight(feature='university', weight=0.9875234887994105, std=None, value=None), FeatureWeight(feature='use', weight=0.9710223786388302, std=None, value=None), FeatureWeight(feature='organization', weight=0.8898678423718357, std=None, value=None), FeatureWeight(feature='subject', weight=0.8886499440484018, std=None, value=None), FeatureWeight(feature='get', weight=0.8196108045672269, std=None, value=None), FeatureWeight(feature='then', weight=0.7116950757101445, std=None, value=None), FeatureWeight(feature='also', weight=0.7073581927514299, std=None, value=None), FeatureWeight(feature='only', weight=0.6610643970607236, std=None, value=None), FeatureWeight(feature='ax', weight=0.6598333593007583, std=None, value=None), FeatureWeight(feature='any', weight=0.6023631941361082, std=None, value=None)], neg=[FeatureWeight(feature='people', weight=-1.6454288386026725, std=None, value=None), FeatureWeight(feature='re', weight=-1.2962703167410945, std=None, value=None), FeatureWeight(feature='his', weight=-1.0759165369553578, std=None, value=None), FeatureWeight(feature='their', weight=-1.0567595723945222, std=None, value=None), FeatureWeight(feature='who', weight=-0.9700667586888111, std=None, value=None), FeatureWeight(feature='writes', weight=-0.7986098811188821, std=None, value=None), FeatureWeight(feature='he', weight=-0.7961913160843334, std=None, value=None), FeatureWeight(feature='these', weight=-0.6186845333689496, std=None, value=None)], pos_remaining=38, neg_remaining=43), proba=None, score=None, weighted_spans=None, heatmap=None)], feature_importances=None, decision_tree=None, highlight_spaces=None, transition_features=None, image=None)