In [1]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

%pylab inline
newsgroups_train = fetch_20newsgroups(subset='train')
newsgroups_test = fetch_20newsgroups(subset='test')

Populating the interactive namespace from numpy and matplotlib


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=100)
cv.fit(newsgroups_train['data'])

CountVectorizer(max_features=100)

In [3]:
X_train = cv.transform(newsgroups_train['data'])
X_test = cv.transform(newsgroups_test['data'])

y_train = newsgroups_train['target']
y_test = newsgroups_test['target']

In [4]:
train_mask = (y_train <= 1)
test_mask = (y_test <= 1)

X_train = X_train[train_mask]
X_test = X_test[test_mask]

y_train = y_train[train_mask]
y_test = y_test[test_mask]

In [5]:
X_train

<1064x100 sparse matrix of type '<class 'numpy.int64'>'
	with 41977 stored elements in Compressed Sparse Row format>

In [6]:
print(X_train.todense())

[[2 0 0 ... 1 1 0]
 [0 1 0 ... 1 2 0]
 [1 5 0 ... 1 2 1]
 ...
 [0 2 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 1 1 0]]


In [7]:
%%time
clf = LogisticRegression(random_state=134).fit(X_train, y_train)

Wall time: 114 ms


C:\Users\ALemikhov\Documents\5th_courth\9th_term\DA_CV\venv\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [8]:
clf.coef_

array([[ 0.21496871, -0.11384424,  0.7311534 ,  0.48705665, -0.42260385,
         0.094515  ,  0.59822667,  0.00846995,  0.15964525, -0.34476092,
         0.45314366,  0.54473344, -0.12165382, -0.23598926, -0.20773231,
         0.30986171, -0.37451187,  1.42639949,  0.11658298, -0.11691015,
         0.11772231, -0.14345485,  0.2839943 , -0.11334614, -0.41722941,
        -0.32348899,  0.42738372,  0.12883422,  0.84222505,  0.13201334,
        -0.00511945,  0.23562563, -0.01588055, -0.78760842, -1.11139986,
         0.09696209,  0.11426275, -0.07952529,  0.06412146, -0.08910738,
        -0.05074342,  0.47139569,  0.02094068,  0.43661826, -0.70061604,
         0.09806651,  0.26838398,  0.33765619, -0.14253297, -0.26548601,
         0.05261228,  0.03483652, -0.32231762, -0.03945235, -0.22840162,
         0.12764263, -0.44253104,  0.65816734, -0.25507359,  0.73324838,
        -0.12170561,  0.53595044, -1.61622365,  0.27528772, -1.32360436,
         0.08397621, -0.04200025, -0.03223417,  0.7

In [9]:
cv.vocabulary_

{'from': 27,
 'edu': 24,
 'my': 49,
 'subject': 68,
 'what': 90,
 'is': 39,
 'this': 79,
 'nntp': 51,
 'posting': 63,
 'host': 35,
 'organization': 59,
 'university': 82,
 'of': 54,
 'lines': 44,
 'was': 86,
 'if': 37,
 'out': 61,
 'there': 75,
 'could': 20,
 'me': 47,
 'on': 55,
 'the': 71,
 'other': 60,
 'it': 40,
 'to': 81,
 'be': 12,
 'were': 89,
 'in': 38,
 'all': 1,
 'know': 42,
 'can': 18,
 'or': 58,
 'you': 98,
 'have': 32,
 'by': 16,
 'your': 99,
 'for': 26,
 'article': 8,
 'who': 93,
 'their': 72,
 'with': 95,
 'and': 5,
 'are': 7,
 'will': 94,
 'so': 66,
 'well': 88,
 'up': 83,
 'as': 9,
 'new': 50,
 'than': 69,
 'that': 70,
 'does': 22,
 'any': 6,
 'when': 91,
 'an': 4,
 'but': 15,
 'don': 23,
 'had': 30,
 'more': 48,
 'has': 31,
 'about': 0,
 'like': 43,
 'just': 41,
 'how': 36,
 'good': 29,
 'some': 67,
 'people': 62,
 'use': 85,
 'get': 28,
 'only': 57,
 'time': 80,
 'at': 10,
 're': 64,
 'com': 19,
 'writes': 97,
 'do': 21,
 'no': 52,
 'am': 3,
 'we': 87,
 'because': 13

In [10]:
[(k,v) for k, v in sorted(cv.vocabulary_.items(), key=lambda item: item[1])]

[('about', 0),
 ('all', 1),
 ('also', 2),
 ('am', 3),
 ('an', 4),
 ('and', 5),
 ('any', 6),
 ('are', 7),
 ('article', 8),
 ('as', 9),
 ('at', 10),
 ('ax', 11),
 ('be', 12),
 ('because', 13),
 ('been', 14),
 ('but', 15),
 ('by', 16),
 ('ca', 17),
 ('can', 18),
 ('com', 19),
 ('could', 20),
 ('do', 21),
 ('does', 22),
 ('don', 23),
 ('edu', 24),
 ('even', 25),
 ('for', 26),
 ('from', 27),
 ('get', 28),
 ('good', 29),
 ('had', 30),
 ('has', 31),
 ('have', 32),
 ('he', 33),
 ('his', 34),
 ('host', 35),
 ('how', 36),
 ('if', 37),
 ('in', 38),
 ('is', 39),
 ('it', 40),
 ('just', 41),
 ('know', 42),
 ('like', 43),
 ('lines', 44),
 ('max', 45),
 ('may', 46),
 ('me', 47),
 ('more', 48),
 ('my', 49),
 ('new', 50),
 ('nntp', 51),
 ('no', 52),
 ('not', 53),
 ('of', 54),
 ('on', 55),
 ('one', 56),
 ('only', 57),
 ('or', 58),
 ('organization', 59),
 ('other', 60),
 ('out', 61),
 ('people', 62),
 ('posting', 63),
 ('re', 64),
 ('should', 65),
 ('so', 66),
 ('some', 67),
 ('subject', 68),
 ('than', 69

In [11]:
names = [k for k, v in sorted(cv.vocabulary_.items(), key=lambda item: item[1])]
coef = clf.coef_.ravel()

In [12]:
df = pd.DataFrame(np.array([coef, names]).T, columns=['coef', 'names'])
df.sort_values('coef')

coef       names
30  -0.005119446294711042         had
75   -0.01105220781826196       there
32  -0.015880550672374236        have
67   -0.03223416993886935        some
53   -0.03945235088160711         not
..                    ...         ...
68     0.7563378689044453     subject
28     0.8422250509326602         get
85     0.9613877498621203         use
82     0.9725277835491077  university
17     1.4263994887554874          ca

[100 rows x 2 columns]

In [15]:
import eli5
eli5.explain_weights(clf, feature_names=names)

C:\Users\ALemikhov\Documents\5th_courth\9th_term\DA_CV\venv\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\ALemikhov\Documents\5th_courth\9th_term\DA_CV\venv\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)


Explanation(estimator='LogisticRegression(random_state=134)', description="\nFeatures with largest coefficients.\nCaveats:\n1. Be careful with features which are not\n   independent - weights don't show their importance.\n2. If scale of input features is different then scale of coefficients\n   will also be different, making direct comparison between coefficient values\n   incorrect.\n3. Depending on regularization, rare features sometimes may have high\n   coefficients; this doesn't mean they contribute much to the\n   classification result for most examples.\n", error=None, method='linear model', is_regression=False, targets=[TargetExplanation(target=1, feature_weights=FeatureWeights(pos=[FeatureWeight(feature='<BIAS>', weight=1.5954715862144826, std=None, value=None), FeatureWeight(feature='ca', weight=1.4263994887554874, std=None, value=None), FeatureWeight(feature='university', weight=0.9725277835491077, std=None, value=None), FeatureWeight(feature='use', weight=0.9613877498621203, std=None, value=None), FeatureWeight(feature='get', weight=0.8422250509326602, std=None, value=None), FeatureWeight(feature='subject', weight=0.7563378689044453, std=None, value=None), FeatureWeight(feature='organization', weight=0.7332483838771474, std=None, value=None), FeatureWeight(feature='also', weight=0.7311534009073474, std=None, value=None), FeatureWeight(feature='then', weight=0.7261400937104695, std=None, value=None), FeatureWeight(feature='only', weight=0.658167343324152, std=None, value=None), FeatureWeight(feature='any', weight=0.5982266729787513, std=None, value=None)], neg=[FeatureWeight(feature='people', weight=-1.616223647716297, std=None, value=None), FeatureWeight(feature='re', weight=-1.3236043581227426, std=None, value=None), FeatureWeight(feature='his', weight=-1.1113998607395044, std=None, value=None), FeatureWeight(feature='their', weight=-1.0566133667298334, std=None, value=None), FeatureWeight(feature='who', weight=-0.9777936646065853, std=None, value=None), FeatureWeight(feature='writes', weight=-0.8110253332567164, std=None, value=None), FeatureWeight(feature='he', weight=-0.7876084167706546, std=None, value=None), FeatureWeight(feature='lines', weight=-0.700616042030194, std=None, value=None), FeatureWeight(feature='these', weight=-0.6087246693660198, std=None, value=None)], pos_remaining=39, neg_remaining=42), proba=None, score=None, weighted_spans=None, heatmap=None)], feature_importances=None, decision_tree=None, highlight_spaces=None, transition_features=None, image=None)